import type { Metadata } from "next";
import Script from "next/script";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <head>
        {/* Google Adsense */}
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2493250444458383"
          crossOrigin="anonymous"
          strategy="afterInteractive"
        />

        {/* Ad Manager */}
        <Script id="adsense-admanager" strategy="afterInteractive">
          {`
            class AdManager {
              constructor() {
                if (window.__adManager) return window.__adManager;
                this.adLoaded = false;
                this.initialized = false;
                window.__adManager = this;
                this.init();
              }

              init() {
                if (this.initialized) return;
                this.initialized = true;
                window.adsbygoogle = window.adsbygoogle || [];
                this.adBreak = (o) => window.adsbygoogle.push(o);

                this.adBreak({
                  preloadAdBreaks: "on",
                  sound: "on",
                  onReady: () => {
                    this.adLoaded = true;
                  },
                });
              }

              showStartAd(callback) {
                if (!this.adLoaded) {
                  callback({});
                  return;
                }

                this.adBreak({
                  type: "start",
                  name: "fullscreen-start",
                  adBreakDone: (result) => {
                    callback(result || {});
                  },
                });
              }
            }

            window.ads = new AdManager();
          `}
        </Script>
      </head>

      <body className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}